apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-bucket-uploader
  namespace: flex
  labels:
    team: flex
spec:
  gcp:
    buckets:
      - name: flex-reisetilskudd-kvitteringer
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: false
  ingresses:
    - "https://flex-bucket-uploader.dev-gcp.nais.io"
  webproxy: true
  env:
    - name: BUCKET_NAME
      value: flex-reisetilskudd-kvitteringer
    - name: OIDC_WELLKNOWN_URI
      value: "https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1"
    - name: LOGINSERVICE_CLIENTID
      value: "0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5"
  accessPolicy:
    outbound:
      external:
        - host: www.googleapis.com
        - host: storage.googleapis.com
        - host: oauth2.googleapis.com
        - host: login.microsoftonline.com
